name: build_example_nativelink
inputs:
  NATIVELINK_ENGINE_ADDRESS_SECRET:
    description: ''
    required: true
  NATIVELINK_AC_ADDRESS_SECRET:
    description: ''
    required: true
  NATIVELINK_CAS_ADDRESS_SECRET:
    description: ''
    required: true
  NATIVELINK_HEADER_RW_KEY_SECRET:
    description: ''
    required: true
runs:
  using: composite
  steps:
  - name: Build examples/remote_execution/nativelink directory
    run: |-
      echo "[buck2_re_client]
      engine_address       = $NATIVELINK_ENGINE_ADDRESS
      action_cache_address = $NATIVELINK_AC_ADDRESS
      cas_address          = $NATIVELINK_CAS_ADDRESS
      http_headers         = x-nativelink-api-key:$NATIVELINK_HEADER_RW_KEY
      tls = true
      instance_name = main
      enabled = true
      capabilities = true
      [build]
      execution_platforms = root//platforms:platforms" > examples/remote_execution/nativelink/.buckconfig.local
      cd examples/remote_execution/nativelink
      export BUCK2_RE_DOWNLOAD_CONCURRENCY=25
      $RUNNER_TEMP/artifacts/buck2 build //... -v 1 --show-simple-output --ui re --ui io --ui dice --ui debugevents --num-threads 10
    env:
      NATIVELINK_ENGINE_ADDRESS: ${{ inputs.NATIVELINK_ENGINE_ADDRESS_SECRET }}
      NATIVELINK_AC_ADDRESS: ${{ inputs.NATIVELINK_AC_ADDRESS_SECRET }}
      NATIVELINK_CAS_ADDRESS: ${{ inputs.NATIVELINK_CAS_ADDRESS_SECRET }}
      NATIVELINK_HEADER_RW_KEY: ${{ inputs.NATIVELINK_HEADER_RW_KEY_SECRET }}
    shell: bash
