name: build_example_nativelink
inputs:
  NATIVELINK_ENGINE_ADDRESS_SECRET:
    description: ''
    required: true
  NATIVELINK_AC_ADDRESS_SECRET:
    description: ''
    required: true
  NATIVELINK_CAS_ADDRESS_SECRET:
    description: ''
    required: true
  NATIVELINK_HEADER_RW_KEY_SECRET:
    description: ''
    required: true
runs:
  using: composite
  steps:
  - name: Build examples/remote_execution/nativelink directory
    run: |-
      sed -i'' -e "s|NATIVELINK_ENGINE_ADDRESS|$NATIVELINK_ENGINE_ADDRESS|" \
                -e "s|NATIVELINK_AC_ADDRESS|$NATIVELINK_AC_ADDRESS|" \
                -e "s|NATIVELINK_CAS_ADDRESS|$NATIVELINK_CAS_ADDRESS|" \
                -e "s|NATIVELINK_HEADER_RW_KEY|$NATIVELINK_HEADER_RW_KEY|" \
                examples/remote_execution/nativelink/.buckconfig
      cd examples/remote_execution/nativelink
      $RUNNER_TEMP/artifacts/buck2 build //... -v 4
    env:
      NATIVELINK_ENGINE_ADDRESS: ${{ inputs.NATIVELINK_ENGINE_ADDRESS_SECRET }}
      NATIVELINK_AC_ADDRESS: ${{ inputs.NATIVELINK_AC_ADDRESS_SECRET }}
      NATIVELINK_CAS_ADDRESS: ${{ inputs.NATIVELINK_CAS_ADDRESS_SECRET }}
      NATIVELINK_HEADER_RW_KEY: ${{ inputs.NATIVELINK_HEADER_RW_KEY_SECRET }}
    shell: bash
