name: Build and test nativelink
on:
  push:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: ["rebase upstream manual", "rebase upstream cron"]
    types:
      - completed
jobs:
  linux-build-examples:
    runs-on: xlarge-ubuntu-x86-22.04
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: ./.github/actions/setup_linux_env
    - uses: ./.github/actions/init_opam
    - uses: ./.github/actions/build_debug
    - uses: ./.github/actions/build_example_nativelink
      with:
        NATIVELINK_ENGINE_ADDRESS_SECRET: ${{ secrets.NATIVELINK_ENGINE_ADDRESS_SECRET }}
        NATIVELINK_AC_ADDRESS_SECRET: ${{ secrets.NATIVELINK_AC_ADDRESS_SECRET }}
        NATIVELINK_CAS_ADDRESS_SECRET: ${{ secrets.NATIVELINK_CAS_ADDRESS_SECRET }}
        NATIVELINK_HEADER_RW_KEY_SECRET: ${{ secrets.NATIVELINK_HEADER_RW_KEY_SECRET }}
    - uses: ./.github/actions/build_example_no_prelude
      with:
        NATIVELINK_ENGINE_ADDRESS_SECRET: ${{ secrets.NATIVELINK_ENGINE_ADDRESS_SECRET }}
        NATIVELINK_AC_ADDRESS_SECRET: ${{ secrets.NATIVELINK_AC_ADDRESS_SECRET }}
        NATIVELINK_CAS_ADDRESS_SECRET: ${{ secrets.NATIVELINK_CAS_ADDRESS_SECRET }}
        NATIVELINK_HEADER_RW_KEY_SECRET: ${{ secrets.NATIVELINK_HEADER_RW_KEY_SECRET }}
    - uses: ./.github/actions/setup_reindeer
    - uses: ./.github/actions/build_bootstrap
